export const marketsConstants = {
    GET_MARKET_PRICES_REQUEST: 'GET_MARKET_PRICES_REQUEST',
    GET_MARKET_PRICES_SUCCESS: 'GET_MARKET_PRICES_SUCCESS',
    GET_MARKET_PRICES_FAILURE: 'GET_MARKET_PRICES_FAILURE'
};
